#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
app.swagger:
    path: /api/documentation
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }